# Generated by Django 6.0.4 on 2026-05-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag_code',
            field=models.CharField(max_length=6),
        ),
    ]
