# Generated by Django 6.0.4 on 2026-05-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0002_alter_team_flag_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
