# Generated by Django 6.0.4 on 2026-05-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0003_match_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
