# Generated by Django 6.0.4 on 2026-05-05 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0004_match_group_alter_match_away_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='prode.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='prode.team'),
        ),
    ]
